-- Démarrer une transaction
BEGIN;

-- Insérer des utilisateurs dans la table user
INSERT INTO "user" (firstname, lastname, email, password, image, location, bio, created_at, updated_at) VALUES
('Jean', 'Dupont', 'jean.dupont@example.com', 'motdepasselong1', NULL, 'Paris', 'Développeur web passionné par les nouvelles technologies.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Marie', 'Curie', 'marie.curie@example.com', 'motdepasselong2', NULL, 'Lyon', 'Designer UI/UX avec une expérience en création de sites web.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Alice', 'Martin', 'alice.martin@example.com', 'motdepasselong3', NULL, 'Marseille', 'Spécialiste en SEO et marketing digital.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Pierre', 'Durand', 'pierre.durand@example.com', 'motdepasselong4', NULL, 'Toulouse', 'Chef de projet Agile avec une forte expérience en gestion d''équipe.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Claire', 'Lefevre', 'claire.lefevre@example.com', 'motdepasselong5', NULL, 'Nice', 'Administratrice réseau avec une expertise en sécurité informatique.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('David', 'Moreau', 'david.moreau@example.com', 'motdepasselong6', NULL, 'Nantes', 'Développeur mobile spécialisé en applications iOS et Android.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Eva', 'Roux', 'eva.roux@example.com', 'motdepasselong7', NULL, 'Strasbourg', 'Graphiste créative avec une passion pour le design visuel.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('François', 'Petit', 'francois.petit@example.com', 'motdepasselong8', NULL, 'Montpellier', 'Expert en publicité en ligne et stratégies de marketing.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Géraldine', 'Blanc', 'geraldine.blanc@example.com', 'motdepasselong9', NULL, 'Bordeaux', 'Analyste de données avec une expérience en Big Data.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hugo', 'Garcia', 'hugo.garcia@example.com', 'motdepasselong10', NULL, 'Lille', 'Ingénieur DevOps avec une expertise en automatisation CI/CD.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Sophie', 'Bernard', 'sophie.bernard@example.com', 'motdepasselong11', NULL, 'Rennes', 'Spécialiste en sécurité des réseaux et protection des données.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Lucas', 'Martinez', 'lucas.martinez@example.com', 'motdepasselong12', NULL, 'Reims', 'Technicien support utilisateur avec une forte expérience en assistance technique.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Emma', 'Lopez', 'emma.lopez@example.com', 'motdepasselong13', NULL, 'Le Havre', 'Rédactrice technique avec une expertise en documentation logicielle.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Louis', 'Morel', 'louis.morel@example.com', 'motdepasselong14', NULL, 'Saint-Étienne', 'Développeur web passionné par les nouvelles technologies.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Chloé', 'Fournier', 'chloe.fournier@example.com', 'motdepasselong15', NULL, 'Toulon', 'Designer UI/UX avec une expérience en création de sites web.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Thomas', 'Girard', 'thomas.girard@example.com', 'motdepasselong16', NULL, 'Grenoble', 'Spécialiste en SEO et marketing digital.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Camille', 'Lemoine', 'camille.lemoine@example.com', 'motdepasselong17', NULL, 'Dijon', 'Chef de projet Agile avec une forte expérience en gestion d''équipe.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Nathan', 'Renaud', 'nathan.renaud@example.com', 'motdepasselong18', NULL, 'Angers', 'Administrateur réseau avec une expertise en sécurité informatique.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Léa', 'Dumont', 'lea.dumont@example.com', 'motdepasselong19', NULL, 'Villeurbanne', 'Développeuse mobile spécialisée en applications iOS et Android.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Julien', 'Gauthier', 'julien.gauthier@example.com', 'motdepasselong20', NULL, 'Clermont-Ferrand', 'Graphiste créatif avec une passion pour le design visuel.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Manon', 'Perrin', 'manon.perrin@example.com', 'motdepasselong21', NULL, 'Aix-en-Provence', 'Experte en publicité en ligne et stratégies de marketing.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Maxime', 'Faure', 'maxime.faure@example.com', 'motdepasselong22', NULL, 'Brest', 'Analyste de données avec une expérience en Big Data.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Sarah', 'Roux', 'sarah.roux@example.com', 'motdepasselong23', NULL, 'Limoges', 'Ingénieure DevOps avec une expertise en automatisation CI/CD.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Antoine', 'Vincent', 'antoine.vincent@example.com', 'motdepasselong24', NULL, 'Tours', 'Spécialiste en sécurité des réseaux et protection des données.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Laura', 'Henry', 'laura.henry@example.com', 'motdepasselong25', NULL, 'Amiens', 'Technicienne support utilisateur avec une forte expérience en assistance technique.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Alexandre', 'Roussel', 'alexandre.roussel@example.com', 'motdepasselong26', NULL, 'Metz', 'Rédacteur technique avec une expertise en documentation logicielle.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Julie', 'Garnier', 'julie.garnier@example.com', 'motdepasselong27', NULL, 'Besançon', 'Développeuse web passionnée par les nouvelles technologies.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Benoît', 'Chevalier', 'benoit.chevalier@example.com', 'motdepasselong28', NULL, 'Orléans', 'Designer UI/UX avec une expérience en création de sites web.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Pauline', 'Caron', 'pauline.caron@example.com', 'motdepasselong29', NULL, 'Mulhouse', 'Spécialiste en SEO et marketing digital.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Guillaume', 'Colin', 'guillaume.colin@example.com', 'motdepasselong30', NULL, 'Rouen', 'Chef de projet Agile avec une forte expérience en gestion d''équipe.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Charlotte', 'Boyer', 'charlotte.boyer@example.com', 'motdepasselong31', NULL, 'Caen', 'Administratrice réseau avec une expertise en sécurité informatique.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Adrien', 'Aubert', 'adrien.aubert@example.com', 'motdepasselong32', NULL, 'Nancy', 'Développeur mobile spécialisé en applications iOS et Android.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Elodie', 'Poulain', 'elodie.poulain@example.com', 'motdepasselong33', NULL, 'Saint-Denis', 'Graphiste créative avec une passion pour le design visuel.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Baptiste', 'Leclerc', 'baptiste.leclerc@example.com', 'motdepasselong34', NULL, 'Argenteuil', 'Expert en publicité en ligne et stratégies de marketing.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Clara', 'Guillot', 'clara.guillot@example.com', 'motdepasselong35', NULL, 'Montreuil', 'Analyste de données avec une expérience en Big Data.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Victor', 'Masson', 'victor.masson@example.com', 'motdepasselong36', NULL, 'Perpignan', 'Ingénieur DevOps avec une expertise en automatisation CI/CD.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Anaïs', 'Marchand', 'anais.marchand@example.com', 'motdepasselong37', NULL, 'Nanterre', 'Spécialiste en sécurité des réseaux et protection des données.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Quentin', 'Duval', 'quentin.duval@example.com', 'motdepasselong38', NULL, 'Avignon', 'Technicien support utilisateur avec une forte expérience en assistance technique.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Mélanie', 'Denis', 'melanie.denis@example.com', 'motdepasselong39', NULL, 'Créteil', 'Rédactrice technique avec une expertise en documentation logicielle.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Florian', 'Lemoine', 'florian.lemoine@example.com', 'motdepasselong40', NULL, 'Poitiers', 'Développeur web passionné par les nouvelles technologies.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Amandine', 'Giraud', 'amandine.giraud@example.com', 'motdepasselong41', NULL, 'Versailles', 'Designer UI/UX avec une expérience en création de sites web.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Romain', 'Barbier', 'romain.barbier@example.com', 'motdepasselong42', NULL, 'Pau', 'Spécialiste en SEO et marketing digital.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Aurélie', 'Meyer', 'aurelie.meyer@example.com', 'motdepasselong43', NULL, 'Colmar', 'Chef de projet Agile avec une forte expérience en gestion d''équipe.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Damien', 'Royer', 'damien.royer@example.com', 'motdepasselong44', NULL, 'La Rochelle', 'Administrateur réseau avec une expertise en sécurité informatique.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Céline', 'Pires', 'celine.pires@example.com', 'motdepasselong45', NULL, 'Antibes', 'Développeuse mobile spécialisée en applications iOS et Android.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vincent', 'Lemoine', 'vincent.lemoine@example.com', 'motdepasselong46', NULL, 'Calais', 'Graphiste créatif avec une passion pour le design visuel.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Isabelle', 'Renard', 'isabelle.renard@example.com', 'motdepasselong47', NULL, 'Boulogne-Billancourt', 'Experte en publicité en ligne et stratégies de marketing.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Thibault', 'Gonzalez', 'thibault.gonzalez@example.com', 'motdepasselong48', NULL, 'Cannes', 'Analyste de données avec une expérience en Big Data.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Nicolas', 'Fontaine', 'nicolas.fontaine@example.com', 'motdepasselong49', NULL, 'Drancy', 'Ingénieur DevOps avec une expertise en automatisation CI/CD.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Valérie', 'Lambert', 'valerie.lambert@example.com', 'motdepasselong50', NULL, 'Ajaccio', 'Spécialiste en sécurité des réseaux et protection des données.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insérer des catégories dans la table category
INSERT INTO category (name, created_at, updated_at) VALUES
('Programmation', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Design', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Art', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Sport', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Artisanat', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cuisine', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Musique', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Écriture', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insérer des compétences dans la table skill
INSERT INTO skill (description, category_id, created_at, updated_at) VALUES
('React', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Python', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('UI/UX Design', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Peinture à l''huile', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Sculpture', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Yoga', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Escalade', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Randonnée', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Poterie', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tricot', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cuisine végétarienne', 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cuisine asiatique', 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Guitare', 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Piano', 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Écriture créative', 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Rédaction de contenu', 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Développement Web', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Graphisme', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Photographie', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insérer des disponibilités dans la table availability
INSERT INTO availability (user_id, date, start_time, end_time, created_at, updated_at) VALUES
(1, '2025-03-01', '09:00:00', '12:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '2025-03-02', '14:00:00', '17:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '2025-03-03', '18:00:00', '21:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '2025-03-02', '13:00:00', '16:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '2025-03-04', '09:00:00', '12:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '2025-03-05', '14:00:00', '17:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, '2025-03-03', '10:00:00', '14:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, '2025-03-06', '13:00:00', '16:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, '2025-03-07', '17:00:00', '20:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, '2025-03-04', '08:00:00', '11:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, '2025-03-05', '12:00:00', '15:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, '2025-03-08', '14:00:00', '17:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, '2025-03-05', '15:00:00', '18:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, '2025-03-07', '09:00:00', '12:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, '2025-03-10', '18:00:00', '21:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, '2025-03-06', '09:00:00', '12:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, '2025-03-08', '14:00:00', '17:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, '2025-03-09', '18:00:00', '21:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, '2025-03-07', '13:00:00', '16:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, '2025-03-10', '10:00:00', '13:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, '2025-03-11', '14:00:00', '17:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, '2025-03-08', '10:00:00', '13:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, '2025-03-09', '14:00:00', '17:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, '2025-03-12', '18:00:00', '21:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, '2025-03-09', '08:00:00', '11:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, '2025-03-10', '14:00:00', '17:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, '2025-03-11', '18:00:00', '21:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, '2025-03-10', '15:00:00', '18:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, '2025-03-12', '09:00:00', '12:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, '2025-03-13', '13:00:00', '16:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, '2025-03-11', '09:00:00', '12:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, '2025-03-13', '13:00:00', '16:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, '2025-03-14', '18:00:00', '21:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, '2025-03-12', '13:00:00', '16:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, '2025-03-14', '14:00:00', '17:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, '2025-03-16', '09:00:00', '12:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, '2025-03-13', '10:00:00', '13:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, '2025-03-14', '14:00:00', '17:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, '2025-03-16', '18:00:00', '21:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, '2025-03-14', '08:00:00', '11:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, '2025-03-15', '12:00:00', '15:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, '2025-03-17', '14:00:00', '17:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, '2025-03-15', '15:00:00', '18:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, '2025-03-17', '09:00:00', '12:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, '2025-03-18', '13:00:00', '16:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(16, '2025-03-16', '09:00:00', '12:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(16, '2025-03-17', '13:00:00', '16:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(16, '2025-03-18', '18:00:00', '21:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, '2025-03-17', '13:00:00', '16:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, '2025-03-18', '14:00:00', '17:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, '2025-03-20', '10:00:00', '13:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, '2025-03-18', '10:00:00', '13:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, '2025-03-19', '14:00:00', '17:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, '2025-03-20', '18:00:00', '21:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, '2025-03-19', '08:00:00', '11:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, '2025-03-20', '13:00:00', '16:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, '2025-03-21', '17:00:00', '20:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, '2025-03-20', '15:00:00', '18:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, '2025-03-21', '09:00:00', '12:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, '2025-03-22', '13:00:00', '16:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(21, '2025-03-21', '09:00:00', '12:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(21, '2025-03-22', '13:00:00', '16:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(21, '2025-03-23', '17:00:00', '20:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, '2025-03-22', '13:00:00', '16:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, '2025-03-23', '10:00:00', '13:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, '2025-03-24', '18:00:00', '21:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, '2025-03-23', '10:00:00', '13:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, '2025-03-24', '14:00:00', '17:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, '2025-03-25', '18:00:00', '21:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, '2025-03-24', '08:00:00', '11:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, '2025-03-25', '14:00:00', '17:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, '2025-03-26', '10:00:00', '13:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(25, '2025-03-25', '15:00:00', '18:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(25, '2025-03-26', '09:00:00', '12:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(25, '2025-03-27', '13:00:00', '16:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(26, '2025-03-01', '09:00:00', '12:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(26, '2025-03-02', '14:00:00', '17:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(26, '2025-03-03', '18:00:00', '21:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(27, '2025-03-02', '13:00:00', '16:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(27, '2025-03-04', '09:00:00', '12:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(27, '2025-03-05', '14:00:00', '17:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(28, '2025-03-03', '10:00:00', '14:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(28, '2025-03-06', '13:00:00', '16:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(28, '2025-03-07', '17:00:00', '20:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, '2025-03-04', '08:00:00', '11:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, '2025-03-05', '12:00:00', '15:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, '2025-03-08', '14:00:00', '17:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(30, '2025-03-05', '15:00:00', '18:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(30, '2025-03-07', '09:00:00', '12:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(30, '2025-03-10', '18:00:00', '21:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(31, '2025-03-06', '09:00:00', '12:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(31, '2025-03-08', '14:00:00', '17:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(31, '2025-03-09', '18:00:00', '21:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(32, '2025-03-07', '13:00:00', '16:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(32, '2025-03-10', '10:00:00', '13:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(32, '2025-03-11', '14:00:00', '17:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(33, '2025-03-08', '10:00:00', '13:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(33, '2025-03-09', '14:00:00', '17:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(33, '2025-03-12', '18:00:00', '21:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, '2025-03-09', '08:00:00', '11:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, '2025-03-10', '14:00:00', '17:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, '2025-03-11', '18:00:00', '21:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, '2025-03-10', '15:00:00', '18:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, '2025-03-12', '09:00:00', '12:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, '2025-03-13', '13:00:00', '16:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(36, '2025-03-11', '09:00:00', '12:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(36, '2025-03-13', '13:00:00', '16:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(36, '2025-03-14', '18:00:00', '21:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(37, '2025-03-12', '13:00:00', '16:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(37, '2025-03-14', '14:00:00', '17:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(37, '2025-03-16', '09:00:00', '12:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(38, '2025-03-13', '10:00:00', '13:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(38, '2025-03-14', '14:00:00', '17:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(38, '2025-03-16', '18:00:00', '21:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(39, '2025-03-14', '08:00:00', '11:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(39, '2025-03-15', '12:00:00', '15:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(39, '2025-03-17', '14:00:00', '17:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(40, '2025-03-15', '15:00:00', '18:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(40, '2025-03-17', '09:00:00', '12:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(40, '2025-03-18', '13:00:00', '16:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insérer des messages dans la table message
INSERT INTO message (sender_id, receiver_id, content, created_at, updated_at) VALUES
(1, 2, 'Bonjour Marie, comment ça va ?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 1, 'Salut Jean, je vais bien merci !', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 4, 'Salut Pierre, tu es disponible pour une réunion ?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 3, 'Oui Alice, je suis disponible demain.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 6, 'Bonjour David, as-tu terminé le projet ?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 5, 'Salut Claire, presque fini !', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 8, 'Bonjour François, peux-tu m''aider avec ce problème ?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 7, 'Bien sûr Eva, je suis là pour t''aider.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 10, 'Salut Hugo, as-tu reçu mon email ?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 9, 'Oui Géraldine, je l''ai reçu.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 12, 'Bonjour Sophie, peux-tu vérifier ce document ?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 11, 'Bien sûr Lucas, je vais le faire.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, 14, 'Salut Emma, as-tu des disponibilités cette semaine ?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 13, 'Oui Louis, je suis libre mercredi.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, 16, 'Bonjour Chloé, peux-tu m''aider avec ce projet ?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(16, 15, 'Oui Thomas, je suis disponible.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, 18, 'Salut Camille, as-tu terminé le rapport ?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, 17, 'Oui Nathan, je l''ai envoyé hier.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, 20, 'Bonjour Léa, peux-tu vérifier ce code ?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, 19, 'Bien sûr Julien, je vais le faire.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(21, 22, 'Salut Manon, as-tu des disponibilités cette semaine ?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 21, 'Oui Maxime, je suis libre jeudi.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, 24, 'Bonjour Sarah, peux-tu m''aider avec ce problème ?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 23, 'Bien sûr Antoine, je suis là pour t''aider.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(25, 26, 'Salut Laura, as-tu reçu mon email ?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(26, 25, 'Oui Alexandre, je l''ai reçu.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(27, 28, 'Bonjour Julie, peux-tu vérifier ce document ?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(28, 27, 'Bien sûr Benoît, je vais le faire.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 30, 'Salut Pauline, as-tu des disponibilités cette semaine ?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(30, 29, 'Oui Guillaume, je suis libre vendredi.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(31, 32, 'Bonjour Charlotte, peux-tu m''aider avec ce projet ?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(32, 31, 'Oui Adrien, je suis disponible.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(33, 34, 'Salut Elodie, as-tu terminé le rapport ?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 33, 'Oui Baptiste, je l''ai envoyé hier.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 36, 'Bonjour Clara, peux-tu vérifier ce code ?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(36, 35, 'Bien sûr Victor, je vais le faire.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(37, 38, 'Salut Anaïs, as-tu des disponibilités cette semaine ?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(38, 37, 'Oui Quentin, je suis libre lundi.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(39, 40, 'Bonjour Mélanie, peux-tu m''aider avec ce problème ?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(40, 39, 'Bien sûr Florian, je suis là pour t''aider.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(41, 42, 'Salut Amandine, as-tu reçu mon email ?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(42, 41, 'Oui Romain, je l''ai reçu.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(43, 44, 'Bonjour Aurélie, peux-tu vérifier ce document ?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(44, 43, 'Bien sûr Damien, je vais le faire.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(45, 46, 'Salut Céline, as-tu des disponibilités cette semaine ?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(46, 45, 'Oui Vincent, je suis libre mardi.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(47, 48, 'Bonjour Isabelle, peux-tu m''aider avec ce projet ?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(48, 47, 'Oui Thibault, je suis disponible.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(49, 50, 'Salut Nicolas, as-tu terminé le rapport ?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(50, 49, 'Oui Valérie, je l''ai envoyé hier.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insérer des évaluations dans la table review
INSERT INTO review (reviewer_id, reviewee_id, rating, review, created_at, updated_at) VALUES
(1, 2, 5, 'Super sympa, toujours dispo pour échanger et donner des conseils.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 1, 4, 'Très agréable à discuter avec, quelques petits retards parfois mais rien de grave.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 4, 3, 'Personne sympa, mais l''échange manquait un peu de fluidité. À améliorer.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 3, 5, 'Top ! Très bon échange, vraiment agréable et ouvert aux idées.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 6, 2, 'Pas assez réactif, mais reste une personne cool.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 5, 4, 'Très abordable et sympathique, j''ai apprécié notre échange.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 8, 3, 'Pas mal, mais on a eu du mal à se comprendre au début. À retravailler.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 7, 5, 'Vraiment une personne agréable à parler, très à l''écoute !', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 2, 4, 'Super échange, mais il manque un petit peu de disponibilité.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 4, 5, 'Très bonne interaction, très respectueux et super sympa !', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 3, 4, 'Très cool, mais un peu plus de clarté dans les échanges serait top.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 6, 5, 'Un vrai plaisir de discuter avec toi, tu es super détendu et agréable !', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, 8, 3, 'Sympathique mais l''échange était un peu trop court. À refaire !', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 1, 4, 'Personne très sympa, mais j''ai eu du mal à avoir des réponses rapidement.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, 7, 5, 'Super échange, vraiment cool et agréable à discuter. On se refait ça !', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(16, 2, 4, 'Très sympa, mais un peu plus d''organisation serait super.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, 3, 5, 'Vraiment une personne chouette, agréable et pleine d''idées intéressantes !', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, 6, 4, 'Sympathique et très ouvert, mais un peu plus de clarté dans l''échange serait top.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, 5, 3, 'Assez sympa, mais l''échange manquait un peu de spontanéité.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, 4, 5, 'Super personne, vraiment facile à parler et très ouverte d''esprit.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(21, 2, 4, 'Très agréable, mais un peu plus de réactivité serait apprécié.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 1, 5, 'Vraiment agréable, une personne chaleureuse et ouverte à la discussion.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, 7, 4, 'Très cool et sympa, mais j''ai eu un peu de mal à obtenir des infos rapidement.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 3, 5, 'Super échange ! Personne positive et super à l''écoute.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(25, 6, 4, 'Vraiment sympa, mais un peu plus de disponibilité serait top.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(26, 8, 5, 'Excellente personne, super ouverte et agréable, j''ai beaucoup apprécié l''échange.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(27, 1, 4, 'Très sympa, mais un peu plus d''engagement serait parfait.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(28, 2, 3, 'Personne agréable, mais un peu trop de silence pendant l''échange.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 5, 4, 'Très cool et sympathique, juste un peu plus de réactivité serait bien.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(30, 7, 5, 'Génial, super échanges et vraiment une personne sympa à discuter.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(31, 4, 4, 'Personne agréable, mais un peu plus de spontanéité serait idéale.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(32, 6, 5, 'J''ai adoré discuter avec toi, très sympa et facile à aborder.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(33, 3, 4, 'Sympathique, mais quelques moments un peu trop lents dans l''échange.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 8, 3, 'Plutôt cool, mais la communication manquait un peu de clarté.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 1, 5, 'Top ! Très agréable à discuter avec, vraiment une personne à l''écoute.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(36, 2, 4, 'Bonne discussion, mais quelques retards parfois. Reste super sympa !', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(37, 5, 3, 'Personne sympa, mais l''échange n''était pas aussi fluide que prévu.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(38, 7, 5, 'Un vrai plaisir d''échanger avec toi, très sympathique et détendu !', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(39, 4, 5, 'Vraiment chouette personne, facile à parler et très positive.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(40, 6, 4, 'Sympathique, mais il manque un peu de réactivité. À améliorer pour la prochaine fois !', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(41, 3, 5, 'Super échange ! Très ouvert et toujours prêt à partager des idées.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(42, 2, 4, 'Vraiment sympa, mais il faudrait un peu plus de temps pour échanger.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(43, 1, 5, 'Génial, un vrai plaisir de discuter. Tu es une personne super agréable !', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(44, 5, 3, 'Sympathique mais on a eu du mal à s''organiser. À améliorer.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(45, 7, 5, 'Super personne, vraiment agréable et ouverte à la discussion, j''adore échanger avec toi.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(46, 4, 4, 'Sympa, mais les échanges étaient un peu trop espacés. Un peu plus d''interaction serait super.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(47, 6, 5, 'Très cool, agréable et toujours dispo pour discuter. Ça fait plaisir !', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(48, 3, 4, 'Vraiment sympa, mais on s''est un peu perdu dans l''échange. À refaire !', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(49, 8, 5, 'Personne super agréable, toujours ouverte et positive, c''est un vrai plaisir !', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(50, 1, 4, 'Sympa, mais quelques réponses un peu lentes. Reste une personne cool !', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 3, 5, 'Très agréable et facile à discuter, super échange !', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 2, 4, 'Personne très sympa, mais un peu plus d''organisation serait bien.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 5, 5, 'Vraiment une personne super, j''ai adoré échanger avec toi !', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 8, 3, 'Sympa mais l''échange était un peu court. À refaire !', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 1, 4, 'Personne super sympa, mais un peu de réactivité manquante.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 4, 5, 'Top ! Très agréable à discuter, je recommande !', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 2, 4, 'Bonne discussion, mais j''ai eu du mal à obtenir des infos rapidement.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 5, 5, 'Super échange ! Personne très sympathique et détendue.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 7, 4, 'Une personne très cool, mais un peu plus de réactivité serait idéal.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 3, 3, 'Sympa, mais la communication pourrait être un peu plus fluide.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 6, 5, 'Un vrai plaisir d''échanger, vraiment une personne à l''écoute !', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, 2, 4, 'Personne agréable, mais un peu plus d''implication serait super.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 1, 5, 'Super sympa ! Très facile à discuter avec et plein de bonnes idées.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, 6, 3, 'Sympa, mais j''ai eu un peu de mal à obtenir des réponses rapidement.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(16, 3, 4, 'Une personne très agréable, mais l''échange a été un peu lent.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, 7, 5, 'Top ! Très agréable à discuter et super sympa.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, 4, 5, 'Génial, j''ai adoré échanger avec toi, super échange !', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, 1, 3, 'Sympa, mais l''échange manquait de réactivité. À améliorer.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, 5, 4, 'Très agréable à discuter, mais un peu plus de temps pour échanger serait top.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(21, 6, 5, 'Super échange ! Personne très ouverte et facile à aborder.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 2, 5, 'Vraiment une personne géniale, facile à discuter et pleine d''idées.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, 7, 3, 'Sympa, mais l''échange n''était pas assez fluide.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 4, 5, 'Excellente personne ! Très agréable et ouverte aux idées.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(25, 6, 4, 'Personne très cool, mais il manque un peu de réactivité dans les échanges.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(26, 2, 5, 'Une personne super sympa, très à l''écoute et très positive.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(27, 1, 4, 'Très agréable à discuter, mais un peu plus d''implication serait top.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(28, 5, 5, 'Top ! Très cool et super ouvert, échange vraiment agréable.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 3, 4, 'Personne sympathique, mais j''ai eu un peu de mal à obtenir des réponses rapidement.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(30, 7, 5, 'Vraiment agréable, super échange ! À refaire sans hésiter.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(31, 2, 5, 'Vraiment génial de discuter avec toi, super échanges et toujours très sympa.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(32, 4, 3, 'Sympa, mais j''aurais aimé des réponses plus claires et plus rapides.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(33, 1, 5, 'Excellente personne, facile à parler et vraiment à l''écoute !', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 5, 4, 'Très cool et agréable, mais un peu plus de clarté serait bien.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 6, 3, 'Pas mal, mais l''échange était un peu trop long à démarrer.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(36, 2, 5, 'Une personne super sympa, toujours ouverte et agréable à discuter.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(37, 1, 4, 'Super échange, mais j''ai eu un peu de mal à comprendre certaines idées.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(38, 7, 5, 'Vraiment une personne géniale à discuter. À refaire sans hésiter !', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(39, 4, 5, 'Excellente discussion, très sympathique et toujours de bonne humeur.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(40, 6, 4, 'Sympathique et agréable, mais j''ai eu du mal à obtenir des réponses rapidement.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(41, 5, 5, 'Très agréable à discuter avec ! Personne positive et super open.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(42, 3, 4, 'Très cool, mais il manque un peu de réactivité. Personne agréable néanmoins.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(43, 2, 5, 'Vraiment une personne super agréable et ouverte à la discussion.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(44, 1, 3, 'Sympa, mais j''ai trouvé l''échange un peu trop long à démarrer.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(45, 6, 5, 'Un vrai plaisir de discuter avec toi ! Super échange et toujours de bonne humeur.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(46, 4, 4, 'Vraiment sympa, mais un peu plus d''interactions auraient été top.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(47, 7, 3, 'Une personne sympa, mais l''échange manquait de fluidité. À améliorer.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(48, 5, 5, 'Super échange ! Personne toujours positive et ouverte aux idées.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(49, 3, 4, 'Sympa, mais l''échange aurait pu être un peu plus rapide.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(50, 6, 5, 'Vraiment chouette échange, très ouvert et agréable à discuter.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insérer des compétences possédées par un utilisateur dans la table user_has_skill
INSERT INTO user_has_skill (user_id, skill_id, description, priority, created_at, updated_at) VALUES
(1, 1, 'Développement en React, création d''interfaces dynamiques et performantes', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 4, 'Création de sites web en Python avec une architecture MVC', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 2, 'Programmation Python avancée, gestion des bases de données', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 7, 'Pratique du yoga pour améliorer la souplesse et la concentration', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 3, 'Conception de sites web modernes en UI/UX Design', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 9, 'Création de contenus visuels à l''aide d''outils de graphisme', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 5, 'Peinture à l''huile, technique de la lumière et des ombres', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 6, 'Sculpture sur bois et pierre', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 4, 'Enseignement et pratique du yoga', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 8, 'Escalade en montagne et en salle', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 10, 'Fabrication de poterie artisanale, travail de l''argile', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 11, 'Tricot créatif et moderne', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 12, 'Cuisine végétarienne, recettes équilibrées', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 13, 'Cuisine asiatique, spécialités chinoises et japonaises', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 14, 'Apprentissage de la guitare, techniques de base', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 15, 'Maîtrise du piano classique et moderne', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 16, 'Écriture créative, développement d''idées et de personnages', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 17, 'Rédaction de contenu SEO, création d''articles pour le web', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 1, 'Développement d''applications web en React', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 14, 'Composition musicale à la guitare', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 18, 'Développement Web en JavaScript, création de sites responsives', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 7, 'Pratique du yoga et méditation', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 2, 'Programmation Python pour l''automatisation des tâches', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 10, 'Création de poteries artisanales pour la décoration', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, 9, 'Graphisme numérique pour la conception de logos', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, 16, 'Écriture de romans historiques et fantastiques', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 5, 'Peinture à l''huile de paysages', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 11, 'Tricot de vêtements et accessoires', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, 4, 'Entraînement physique et pratique du yoga pour débutants', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, 13, 'Cuisine asiatique, préparation de sushis et de plats à base de riz', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(16, 2, 'Programmation Python pour le traitement de données', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(16, 15, 'Piano jazz et improvisation musicale', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, 12, 'Cuisine végétarienne, plats à base de légumes frais', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, 3, 'UI/UX Design, création de maquettes fonctionnelles', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, 8, 'Escalade en milieu naturel', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, 6, 'Sculpture sur métal et bois', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, 7, 'Randonnée en montagne, préparation et sécurité', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, 16, 'Rédaction d''articles pour blogs et magazines', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, 18, 'Développement web en PHP et JavaScript', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, 9, 'Photographie de portrait et de paysages', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(21, 14, 'Guitare acoustique et électrique, apprentissage des accords', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(21, 2, 'Développement d''API en Python', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 6, 'Sculpture sur pierre, techniques avancées', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 18, 'Création de sites web avec HTML, CSS et JavaScript', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, 3, 'UI/UX Design, création de prototypes interactifs', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, 13, 'Cuisine asiatique, spécialités vietnamiennes et thaïlandaises', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 5, 'Peinture à l''huile de portraits et scènes de la vie quotidienne', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 7, 'Escalade en falaise et parcours techniques', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(25, 15, 'Piano classique, étude des partitions', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(25, 4, 'Yoga et méditation guidée pour améliorer la santé', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(26, 9, 'Graphisme pour la création de supports marketing', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(26, 16, 'Écriture d''articles scientifiques et techniques', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(27, 6, 'Sculpture et modélisation 3D', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(27, 12, 'Cuisine végétarienne, spécialités indiennes', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(28, 3, 'UI/UX Design pour la conception d''applications mobiles', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(28, 2, 'Programmation Python et gestion de bases de données', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 7, 'Pratique du yoga en pleine nature', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 13, 'Cuisine asiatique, préparation de sushis', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(30, 5, 'Peinture à l''huile, techniques modernes et classiques', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(30, 6, 'Sculpture contemporaine', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(31, 2, 'Programmation Python pour l''analyse de données', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(31, 16, 'Écriture créative, rédaction de scénarios', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(32, 14, 'Apprentissage de la guitare électrique', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(32, 18, 'Développement web avec Node.js et Express', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(33, 7, 'Yoga, techniques de respiration et relaxation', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(33, 5, 'Peinture à l''huile de paysages naturels', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 13, 'Cuisine asiatique, spécialités coréennes et thaïlandaises', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 6, 'Sculpture sur bois, objets décoratifs et utilitaires', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 3, 'UI/UX Design, conception de sites web accessibles', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 12, 'Cuisine végétarienne, soupes et plats à base de légumineuses', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(36, 9, 'Photographie de produits et portraits', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(36, 7, 'Escalade sur rocher', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(37, 16, 'Rédaction de contenu pour blogs et médias sociaux', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(37, 5, 'Peinture à l''huile pour débutants', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(38, 15, 'Piano classique, maîtrise des gammes et accords', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(38, 2, 'Programmation Python pour les applications web', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(39, 18, 'Développement web avec HTML, CSS et PHP', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(39, 10, 'Création de poteries pour le jardin', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(40, 6, 'Sculpture moderne, utilisation de nouveaux matériaux', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(40, 11, 'Tricot d''accessoires pour enfants', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(41, 4, 'Enseignement du yoga et méditation', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(41, 7, 'Randonnée et exploration de sentiers', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(42, 3, 'UI/UX Design, utilisation de Figma pour la création de prototypes', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(42, 16, 'Écriture de fiction et de poésie', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(43, 9, 'Graphisme pour la création de visuels publicitaires', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(43, 18, 'Développement web pour les applications mobiles', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(44, 12, 'Cuisine asiatique, plats végétariens', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(44, 5, 'Peinture à l''huile, techniques abstraites', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(45, 8, 'Escalade en extérieur, préparation physique', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(45, 10, 'Création de poteries décoratives', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(46, 2, 'Programmation Python, utilisation de pandas pour les analyses', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(46, 12, 'Cuisine végétarienne, recettes équilibrées et faciles', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(47, 13, 'Cuisine asiatique, plats épicés et rapides', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(47, 7, 'Yoga et relaxation en pleine nature', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(48, 18, 'Développement web en React et Node.js', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(48, 10, 'Création de poteries artisanales et utilitaires', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(49, 5, 'Peinture à l''huile, paysages et scènes de la vie quotidienne', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(49, 6, 'Sculpture sur bois, créations pour la décoration intérieure', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(50, 9, 'Photographie de mariage et événements', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(50, 12, 'Cuisine végétarienne, plats à base de tofu', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insérer des compétences recherchées par un utilisateur dans la table user_has_interest
INSERT INTO user_has_interest (user_id, interest_id, priority, created_at, updated_at) VALUES
(1, 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 4, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 5, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 6, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 7, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 8, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 9, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 10, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 11, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 12, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, 13, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(16, 3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, 4, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, 5, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, 6, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, 7, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(21, 8, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 9, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, 10, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 11, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(25, 12, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(26, 13, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(27, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(28, 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(30, 4, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(31, 5, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(32, 6, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(33, 7, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 8, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 9, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(36, 10, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(37, 11, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(38, 12, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(39, 13, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(40, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(41, 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(42, 3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(43, 4, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(44, 5, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(45, 6, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(46, 7, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(47, 8, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(48, 9, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(49, 10, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(50, 11, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insérer des abonnements (followers) dans la table user_has_follower
INSERT INTO user_has_follower (user_id, follower_id, created_at, updated_at) VALUES
(1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 11, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, 14, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 13, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, 16, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(16, 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, 18, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, 17, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, 19, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(21, 22, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 21, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 23, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(25, 26, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(26, 25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(27, 28, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(28, 27, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(30, 29, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(31, 32, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(32, 31, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(33, 34, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 33, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(36, 35, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(37, 38, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(38, 37, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(39, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(40, 39, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(41, 42, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(42, 41, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(43, 44, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(44, 43, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(45, 46, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(46, 45, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(47, 48, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(48, 47, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(49, 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(50, 49, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Valider la transaction
COMMIT;